name: CMake on Ubuntu (build only)

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: jibal

    - name: Install dependencies
      run: sudo apt-get install -y libgsl27 libgsl-dev

    - name: Configure
      run: cmake -B ${{ github.workspace }}/build_jibal -S ${{ github.workspace }}/jibal

    - name: Build
      run: cmake --build ${{ github.workspace }}/build_jibal
